/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VERA } from "./VERA";
export * as factories from "./factories";
export { VERA__factory } from "./factories/VERA__factory";
