/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VERA {
  export type MilestoneStruct = {
    id: BytesLike;
    amount: BigNumberish;
    releasedAmount: BigNumberish;
    requestedReleaseAmount: BigNumberish;
    releaseRequested: boolean;
    released: boolean;
    failed: boolean;
  };

  export type MilestoneStructOutput = [
    id: string,
    amount: bigint,
    releasedAmount: bigint,
    requestedReleaseAmount: bigint,
    releaseRequested: boolean,
    released: boolean,
    failed: boolean
  ] & {
    id: string;
    amount: bigint;
    releasedAmount: bigint;
    requestedReleaseAmount: bigint;
    releaseRequested: boolean;
    released: boolean;
    failed: boolean;
  };
}

export interface VERAInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "approvalCounts"
      | "approveRelease"
      | "approveReleaseFor"
      | "campaigns"
      | "createCampaign"
      | "createMilestone"
      | "donate"
      | "donorContributions"
      | "getCampaign"
      | "getMilestone"
      | "markMilestoneFailed"
      | "milestones"
      | "refund"
      | "releaseApprovals"
      | "releaseFunds"
      | "requestRelease"
      | "setSigners"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "DonationReceived"
      | "FundsReleased"
      | "MilestoneCreated"
      | "MilestoneFailed"
      | "RefundIssued"
      | "ReleaseApproved"
      | "ReleaseRequested"
      | "SignersConfigured"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approvalCounts",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRelease",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveReleaseFor",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [
      BytesLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMilestone",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "donate", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "donorContributions",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markMilestoneFailed",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BytesLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseApprovals",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRelease",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSigners",
    values: [BytesLike, AddressLike, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approvalCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveReleaseFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donorContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markMilestoneFailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSigners", data: BytesLike): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    owner: AddressLike,
    targetAmount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    owner: string,
    targetAmount: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    owner: string;
    targetAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationReceivedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [campaignId: string, donor: string, amount: bigint];
  export interface OutputObject {
    campaignId: string;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    milestoneId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    milestoneId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    milestoneId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneCreatedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    milestoneId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    milestoneId: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    milestoneId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneFailedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    milestoneId: BytesLike,
    reason: string
  ];
  export type OutputTuple = [
    campaignId: string,
    milestoneId: string,
    reason: string
  ];
  export interface OutputObject {
    campaignId: string;
    milestoneId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    campaignId: string,
    recipient: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    campaignId: string;
    recipient: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseApprovedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    milestoneId: BytesLike,
    approver: AddressLike,
    currentApprovals: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    milestoneId: string,
    approver: string,
    currentApprovals: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    milestoneId: string;
    approver: string;
    currentApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseRequestedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    milestoneId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    milestoneId: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    milestoneId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignersConfiguredEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    ngoAdmin: AddressLike,
    campaignOwner: AddressLike,
    auditor: AddressLike
  ];
  export type OutputTuple = [
    campaignId: string,
    ngoAdmin: string,
    campaignOwner: string,
    auditor: string
  ];
  export interface OutputObject {
    campaignId: string;
    ngoAdmin: string;
    campaignOwner: string;
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VERA extends BaseContract {
  connect(runner?: ContractRunner | null): VERA;
  waitForDeployment(): Promise<this>;

  interface: VERAInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  approvalCounts: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  approveRelease: TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike],
    [void],
    "nonpayable"
  >;

  approveReleaseFor: TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, approver: AddressLike],
    [void],
    "nonpayable"
  >;

  campaigns: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string,
        string
      ] & {
        id: string;
        owner: string;
        targetAmount: bigint;
        totalDonated: bigint;
        totalReleased: bigint;
        totalAllocated: bigint;
        active: boolean;
        ngoAdmin: string;
        campaignOwner: string;
        auditor: string;
      }
    ],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [
      campaignId: BytesLike,
      targetAmount: BigNumberish,
      owner: AddressLike,
      ngoAdmin: AddressLike,
      campaignOwner: AddressLike,
      auditor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  createMilestone: TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  donate: TypedContractMethod<[campaignId: BytesLike], [void], "payable">;

  donorContributions: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getCampaign: TypedContractMethod<
    [campaignId: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        owner: string;
        targetAmount: bigint;
        totalDonated: bigint;
        totalReleased: bigint;
        totalAllocated: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getMilestone: TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike],
    [
      [VERA.MilestoneStructOutput, bigint] & {
        milestone: VERA.MilestoneStructOutput;
        currentApprovals: bigint;
      }
    ],
    "view"
  >;

  markMilestoneFailed: TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  milestones: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean, boolean] & {
        id: string;
        amount: bigint;
        releasedAmount: bigint;
        requestedReleaseAmount: bigint;
        releaseRequested: boolean;
        released: boolean;
        failed: boolean;
      }
    ],
    "view"
  >;

  refund: TypedContractMethod<
    [
      campaignId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  releaseApprovals: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike, arg2: AddressLike],
    [boolean],
    "view"
  >;

  releaseFunds: TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  requestRelease: TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSigners: TypedContractMethod<
    [
      campaignId: BytesLike,
      ngoAdmin: AddressLike,
      campaignOwner: AddressLike,
      auditor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approvalCounts"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveRelease"
  ): TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveReleaseFor"
  ): TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, approver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string,
        string
      ] & {
        id: string;
        owner: string;
        targetAmount: bigint;
        totalDonated: bigint;
        totalReleased: bigint;
        totalAllocated: bigint;
        active: boolean;
        ngoAdmin: string;
        campaignOwner: string;
        auditor: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      campaignId: BytesLike,
      targetAmount: BigNumberish,
      owner: AddressLike,
      ngoAdmin: AddressLike,
      campaignOwner: AddressLike,
      auditor: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createMilestone"
  ): TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[campaignId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "donorContributions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        owner: string;
        targetAmount: bigint;
        totalDonated: bigint;
        totalReleased: bigint;
        totalAllocated: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike],
    [
      [VERA.MilestoneStructOutput, bigint] & {
        milestone: VERA.MilestoneStructOutput;
        currentApprovals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markMilestoneFailed"
  ): TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean, boolean] & {
        id: string;
        amount: bigint;
        releasedAmount: bigint;
        requestedReleaseAmount: bigint;
        releaseRequested: boolean;
        released: boolean;
        failed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<
    [
      campaignId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseApprovals"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRelease"
  ): TypedContractMethod<
    [campaignId: BytesLike, milestoneId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSigners"
  ): TypedContractMethod<
    [
      campaignId: BytesLike,
      ngoAdmin: AddressLike,
      campaignOwner: AddressLike,
      auditor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DonationReceived"
  ): TypedContractEvent<
    DonationReceivedEvent.InputTuple,
    DonationReceivedEvent.OutputTuple,
    DonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneCreated"
  ): TypedContractEvent<
    MilestoneCreatedEvent.InputTuple,
    MilestoneCreatedEvent.OutputTuple,
    MilestoneCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneFailed"
  ): TypedContractEvent<
    MilestoneFailedEvent.InputTuple,
    MilestoneFailedEvent.OutputTuple,
    MilestoneFailedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseApproved"
  ): TypedContractEvent<
    ReleaseApprovedEvent.InputTuple,
    ReleaseApprovedEvent.OutputTuple,
    ReleaseApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseRequested"
  ): TypedContractEvent<
    ReleaseRequestedEvent.InputTuple,
    ReleaseRequestedEvent.OutputTuple,
    ReleaseRequestedEvent.OutputObject
  >;
  getEvent(
    key: "SignersConfigured"
  ): TypedContractEvent<
    SignersConfiguredEvent.InputTuple,
    SignersConfiguredEvent.OutputTuple,
    SignersConfiguredEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(bytes32,address,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "DonationReceived(bytes32,address,uint256)": TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;
    DonationReceived: TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;

    "FundsReleased(bytes32,bytes32,address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "MilestoneCreated(bytes32,bytes32,uint256)": TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;
    MilestoneCreated: TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;

    "MilestoneFailed(bytes32,bytes32,string)": TypedContractEvent<
      MilestoneFailedEvent.InputTuple,
      MilestoneFailedEvent.OutputTuple,
      MilestoneFailedEvent.OutputObject
    >;
    MilestoneFailed: TypedContractEvent<
      MilestoneFailedEvent.InputTuple,
      MilestoneFailedEvent.OutputTuple,
      MilestoneFailedEvent.OutputObject
    >;

    "RefundIssued(bytes32,address,uint256,string)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;

    "ReleaseApproved(bytes32,bytes32,address,uint256)": TypedContractEvent<
      ReleaseApprovedEvent.InputTuple,
      ReleaseApprovedEvent.OutputTuple,
      ReleaseApprovedEvent.OutputObject
    >;
    ReleaseApproved: TypedContractEvent<
      ReleaseApprovedEvent.InputTuple,
      ReleaseApprovedEvent.OutputTuple,
      ReleaseApprovedEvent.OutputObject
    >;

    "ReleaseRequested(bytes32,bytes32,uint256)": TypedContractEvent<
      ReleaseRequestedEvent.InputTuple,
      ReleaseRequestedEvent.OutputTuple,
      ReleaseRequestedEvent.OutputObject
    >;
    ReleaseRequested: TypedContractEvent<
      ReleaseRequestedEvent.InputTuple,
      ReleaseRequestedEvent.OutputTuple,
      ReleaseRequestedEvent.OutputObject
    >;

    "SignersConfigured(bytes32,address,address,address)": TypedContractEvent<
      SignersConfiguredEvent.InputTuple,
      SignersConfiguredEvent.OutputTuple,
      SignersConfiguredEvent.OutputObject
    >;
    SignersConfigured: TypedContractEvent<
      SignersConfiguredEvent.InputTuple,
      SignersConfiguredEvent.OutputTuple,
      SignersConfiguredEvent.OutputObject
    >;
  };
}
